### ISSUE TITLE
On Windows 10 Pro I get no luck when refreshing

### ISSUE THREAD

**Issue by MostHated** [poikilos/blendernightly#2]
I tried running this on a Ryzen 5 2600 on Windows 10 Pro with no luck. I ran it with PyCharm and this was the output. I had 2.80 / win64 / win64. Just to test I typed in 2.79 as well as other systems and architectures but it made no difference. Always came back the same, not even an "incorrect OS" or anything when I put in Windowz instead of win64.

Starting refresh thread...

Downloading the html page...
CLEARED dl list since found document decl: DOCTYPE html
CLEARED dl list since found <html...
Of the total 0 blender download url(s)
all:
  matched 0 2.80 url(s)
matching version (tag):
  matched 0 url(s)
  existing_downloads: 
  matched 0 windows1 url(s)
no available downloads are installed yet.

**Comment by poikilos** [comment]
It should work now (the commit made the `absolute_url` method adapt to varying use of slashes in client-side routes).
